### ISSUE TITLE
Missing positional argument "values" with ConditionType BOOLEAN (checkboxes)

### ISSUE THREAD

**Issue by emsearcy** [robin900/gspread-formatting#20]
**Describe the bug**
The ConditionType BOOLEAN BooleanCondition (a checkbox) does not have any values.  Fetching a Checkbox created via the UI returns an error.

**Version and Environment**
*Version of package*: 0.2.4
*Python interpreter*: Python 3.8.3 (via homebrew)
*OS*: macOS Catalina 10.15.5

**To Reproduce**
1. Insert a Checkbox via the UI
2. call get_data_validation_rule on the cell

```
>>> gspread_formatting.get_data_validation_rule(test, 'A2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/redacted/Library/Python/3.8/lib/python/site-packages/gspread_formatting/functions.py", line 165, in get_data_validation_rule
    return DataValidationRule.from_props(props) if props else None
  File "/Users/redacted/Library/Python/3.8/lib/python/site-packages/gspread_formatting/models.py", line 11, in from_props
    return _props_to_component(_CLASSES, _underlower(cls.__name__), props)
  File "/Users/redacted/Library/Python/3.8/lib/python/site-packages/gspread_formatting/util.py", line 98, in _props_to_component
    v = _props_to_component(class_registry, item_alias, v, True)
  File "/Users/redacted/Library/Python/3.8/lib/python/site-packages/gspread_formatting/util.py", line 101, in _props_to_component
    return cls(**kwargs) if (kwargs or not none_if_empty) else None
TypeError: __init__() missing 1 required positional argument: 'values'
```

When creating the rule (for set_data_validation_for_cell_range), it is likewise expected that you would not need a "values" parameter, however this is required:

```
>>> vr = gspread_formatting.DataValidationRule(gspread_formatting.BooleanCondition('BOOLEAN', []))
```
...seems to work, but not obvious / doesn't line up with upstream API docs.

**Expected behavior**

A BooleanCondition of ConditionType BOOLEAN should be able to be instantiated with no `values` positional parameter.

**Comment by robin900** [comment]
@emsearcy Thanks so much for submitting this issue. I will likely be able to provide a fix, with test coverage, and a PyPI release within the next day or two.

**Comment by robin900** [comment]
@emsearcy Release 0.2.5 containing fix now present in PyPI.
