### ISSUE TITLE
No format component named "link"

### ISSUE THREAD

**Issue by beckyjackson** [robin900/gspread-formatting#33]
**Describe the bug**
Explained in "To Reproduce" - unable to create a cell formatting using a link.

**Version and Environment**
*Version of package*: 1.0.0
*Python interpreter*: Python 3
*OS*: Mac OS 11

**To Reproduce**
I retrieve the Google sheet formats from an existing spreadsheet with a hyperlink, and the JSON looks like this:
```
{
    "hyperlinkDisplayType": "LINKED",
    "textFormat": {
        "foregroundColor": {
            "blue": 0.8,
            "green": 0.33333334,
            "red": 0.06666667
        },
        "foregroundColorStyle": {
            "rgbColor": {
                "blue": 0.8,
                "green": 0.33333334,
                "red": 0.06666667
            }
        },
        "link": {
            "uri": "http://google.com/"
        },
        "underline": true
    }
}
```

When I try and apply this formatting using the code below (where `fmt` is the JSON), I get the error: "No format component named 'link'"
```
cell_format = gf.CellFormat.from_props(fmt)
```

Here's a full example:
```
>>> import gspread_formatting as gf
>>> fmt = {
...     "hyperlinkDisplayType": "LINKED",
...     "textFormat": {
...         "foregroundColor": {
...             "blue": 0.8,
...             "green": 0.33333334,
...             "red": 0.06666667
...         },
...         "foregroundColorStyle": {
...             "rgbColor": {
...                 "blue": 0.8,
...                 "green": 0.33333334,
...                 "red": 0.06666667
...             }
...         },
...         "link": {
...             "uri": "http://google.com/"
...         },
...         "underline": True
...     }
... }
>>> cell_format = gf.CellFormat.from_props(fmt)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jackson/opt/anaconda3/lib/python3.8/site-packages/gspread_formatting/models.py", line 14, in from_props
    return _props_to_component(_CLASSES, _underlower(cls.__name__), props)
  File "/Users/jackson/opt/anaconda3/lib/python3.8/site-packages/gspread_formatting/util.py", line 98, in _props_to_component
    v = _props_to_component(class_registry, item_alias, v, True)
  File "/Users/jackson/opt/anaconda3/lib/python3.8/site-packages/gspread_formatting/util.py", line 98, in _props_to_component
    v = _props_to_component(class_registry, item_alias, v, True)
  File "/Users/jackson/opt/anaconda3/lib/python3.8/site-packages/gspread_formatting/util.py", line 89, in _props_to_component
    raise ValueError("No format component named '%s'" % class_alias)
ValueError: No format component named 'link'
```

**Expected behavior**
Since the JSON is coming from the Google API, I would expect the `link` format component to be supported.

**Desktop (please complete the following information):**
 - OS: Mac OS 11
 - Browser: Chrome
 - Version 91

**Comment by beckyjackson** [comment]
Also relevant, here is how I'm retrieving the formats in the first place using `googleapiclient`:

```python
from googleapiclient import discovery

service = discovery.build("sheets", "v4", credentials=credentials, cache=MemoryCache())
request = service.spreadsheets().get(
    spreadsheetId=spreadsheet_id,
    ranges=f"'{sheet_name}'",
    fields="sheets(data(rowData(values(*))))",
)
resp = request.execute()

data = resp["sheets"][0]["data"][0]

for row in data["rowData"]:
    for cell in row["values"]:
        cell_data = {}
        if "userEnteredFormat" in cell:
            # Here's where the "link" comes from
            cell_data["format"] = cell["userEnteredFormat"]
        # more stuff ...
```

**Comment by robin900** [comment]
@beckyjackson Thanks for the through bug report. Release 1.0.1 of this package is now in PyPI and contains the fix to your issue (along with test coverage of the issue). Let me know if the new package version solves your problem!

**Comment by beckyjackson** [comment]
Thanks so much for the quick fix! This works great now.
