### ISSUE TITLE
Breaking change from gspread

### ISSUE THREAD

**Issue by brianeclow** [robin900/gspread-formatting#51]
**Describe the bug**

The new version of `gspread` v6.0.0 has a breaking change

**Version and Environment**
*Version of package*: 1.1.2
*Python interpreter*: python3
*OS*: linux, Mac OS

**To Reproduce**

1. set freeze with passing in worksheet object
2. Error

**Expected behavior**

Freeze should be set

**Screenshots**

```
Traceback (most recent call last):
  File "/Users/brianeclow/dns/./bin/load_harvest", line 172, in <module>
    set_frozen(worksheet, rows=freeze_rows, cols=freeze_cols)
  File "/Users/brianeclow/dns/env/lib/python3.11/site-packages/gspread_formatting/functions.py", line 27, in f
    return worksheet.spreadsheet.batch_update({'requests': func(worksheet, *args, **kwargs)})
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Worksheet' object has no attribute 'spreadsheet'. Did you mean: 'spreadsheet_id'?
```

**Comment by brianeclow** [comment]
Looks live version `6.0.1` of `gspread` solves this issue.
