### ISSUE TITLE
set_row_height gives an error with gspread 6.0.0

### ISSUE THREAD

**Issue by a-n-marey** [robin900/gspread-formatting#58]
**Describe the bug**
I am trying to use set_row_height as I always have been but it gives an error with gspread new version
This gives no error with gspread==5.11.3
but with gspread==6.0.0 it gives the mentioned error

```
import gspread
from gspread_formatting import set_column_width, set_row_height
from oauth2client.service_account import ServiceAccountCredentials

def create_workbook(url, json_creds):    
    # Authenticate and create a gspread client
    # gc = gspread.oauth()
    creds_json_str = json.dumps(json_creds)
    creds = ServiceAccountCredentials.from_json_keyfile_dict(json.loads(creds_json_str))

    gc = gspread.authorize(creds)
    # gc = gspread.service_account(filename="./symmetric-ace-383702-044012652665.json")
    sh = gc.open_by_url(url)
    wks = sh.get_worksheet(0)

    return url, sh, wks, creds
url, sh, wks, creds = create_workbook(url, json_creds=json_creds)

try:
    sheet = sh.worksheet("Plots")
except gspread.exceptions.WorksheetNotFound:
    sheet = sh.add_worksheet(title="Plots", rows="100", cols="5")

set_row_height(sheet, str(row_order + 1), 800)
```

giving me this error 
```
Traceback (most recent call last):
File "/usr/src/app/spreadsheet_logging.py", line 616, in main_spreadsheet_logging
save_plots(new_csv_results, sh, creds)
File "/usr/src/app/spreadsheet_logging.py", line 289, in save_plots
set_row_height(sheet, str(row_order + 1), 800)
File "/usr/local/lib/python3.11/site-packages/gspread_formatting/functions.py", line 27, in f
return worksheet.spreadsheet.batch_update({'requests': func(worksheet, *args, **kwargs)})
```

*OS*: ubuntu

**Comment by robin900** [comment]
@ahmed-retrace Upgrade `gspread` to 6.0.1 or later. Release 6.0.0 contains a bug that broke a lot of packages' behavior, including that of `gspread-formatting`. 

https://github.com/burnash/gspread/releases/tag/v6.0.1
https://github.com/burnash/gspread/issues/1395
